modLoader="javafml"
loaderVersion="[35,)"
license="CC BY-NC-SA 3.0 Unported"
issueTrackerURL="https://github.com/EltrutLikes/Lepton/issues"
[[mods]]
modId="lepton"
version="1.2.0"
displayName="Lepton"
logoFile="examplemod.png"
credits="You for downloading it of course"
authors="EltrutLikes"
description='''
Smallest things.
'''
[[dependencies.lepton]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lepton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.lepton]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"