modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="lepton"
version="0.1.0"
displayName="Lepton"
logoFile="examplemod.png"
credits="You for downloading it of course"
authors="EltrutLikes"
description='''
Smallest things.
'''
[[dependencies.lepton]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lepton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
